import type { Metadata } from "next";

import Sidebar from "@/components/sidebar";

import { SidebarInset, SidebarProvider } from "@/components/ui/sidebar";
import DashboardHeader from "@/components/header";
import DashboardChat from "@/components/assistant/chat-box";

export const metadata: Metadata = {
  title: "Dashbaord",
  description: "Generated by create next app",
};

export default function DashboardLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <main>
      <DashboardChat />
      <SidebarProvider>
        <Sidebar />
        <SidebarInset>
          <div className="flex h-screen flex-col">
            <DashboardHeader />
            <main className="xxl:w-[85%] w-[90%] mx-auto mt-20">
              {children}
            </main>
          </div>
        </SidebarInset>
      </SidebarProvider>
    </main>
  );
}
