import type { Metadata } from "next";

import Sidebar from "@/components/sidebar";

import { SidebarInset, SidebarProvider } from "@/components/ui/sidebar";
import DashboardHeader from "@/components/header";
import DashboardChat from "@/components/assistant/chat-box";
import DashbaordFilterTabs from "@/components/filter-tabs";
import DashboardCustomButton from "@/components/custom-button";

export const metadata: Metadata = {
  title: "Dashbaord",
  description: "Generated by create next app",
};

export default function DashboardLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <main>
      <DashboardChat />
      <SidebarProvider>
        <Sidebar />
        <SidebarInset>
          <div className="flex h-screen flex-col">
            <DashboardHeader />
            <main className="xxl:w-[85%] w-[90%] mx-auto mt-20">
              <div className="space-y-7 w-full">
                <div className="flex justify-between items-center sm:flex-row flex-col  sm:gap-0 gap-y-3 w-full">
                  <DashbaordFilterTabs />
                  <DashboardCustomButton>
                    Create Assessment
                  </DashboardCustomButton>
                </div>
                {children}
              </div>
            </main>
          </div>
        </SidebarInset>
      </SidebarProvider>
    </main>
  );
}
