import type { Metadata } from "next";

import DashboardHeader from "@/components/header";

export const metadata: Metadata = {
  title: "Dashbaord",
  description: "Generated by create next app",
};

export default function AuthLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <main className="w-ful">
      <div className="flex h-screen flex-col w-full">
        <DashboardHeader />
        <div className="flex-1 pt-[60px] pb-[20px] md:pt-[120px]  mx-auto w-full">
          {children}
        </div>
      </div>
    </main>
  );
}
