import type { Metadata } from "next";
import "./globals.css";

import { Lato } from "next/font/google";
import { cn } from "@/lib/utils";

const lato = Lato({
  subsets: ["latin"],
  weight: ["100", "300", "400", "700", "900"],
  variable: "--font-lato",
  display: "swap",
});

export const metadata: Metadata = {
  title: "Dashbaord",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={cn(
          `font-[family-name:var(--font-lato)] antialiased`,
          lato.variable
        )}
      >
        <main className="">{children}</main>
      </body>
    </html>
  );
}
