import type { Metadata } from "next";
import "./globals.css";

import { Lato } from "next/font/google";
import { cn } from "@/lib/utils";
import Sidebar from "@/components/sidebar";

import { SidebarInset, SidebarProvider } from "@/components/ui/sidebar";
import DashboardHeader from "@/components/header";
import DashboardChat from "@/components/assistant/chat-box";

export const lato = Lato({
  subsets: ["latin"],
  weight: ["100", "300", "400", "700", "900"],
  variable: "--font-lato",
  display: "swap",
});

export const metadata: Metadata = {
  title: "Dashbaord",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={cn(
          `font-[family-name:var(--font-lato)] antialiased`,
          lato.variable
        )}
      >
        <DashboardChat />
        <SidebarProvider>
          <Sidebar />
          <SidebarInset>
            <div className="flex h-screen flex-col">
              <DashboardHeader />
              <main className="xxl:w-[85%] w-[90%] mx-auto mt-20">
                {children}
              </main>
            </div>
          </SidebarInset>
        </SidebarProvider>
      </body>
    </html>
  );
}
